name: CI
on:
  push:
  schedule:
    - cron: '0 0 1 * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Checkout testdir
      uses: actions/checkout@v4
      with:
        path: testdir

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Run Test Code
      run: cargo run
